// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvppYMQKkk74cH3vnLaYHDI8qEeOhM3yk',
    appId: '1:624903561185:web:85997558bc206f9cf8fca0',
    messagingSenderId: '624903561185',
    projectId: 'instafeed-60a74',
    authDomain: 'instafeed-60a74.firebaseapp.com',
    storageBucket: 'instafeed-60a74.appspot.com',
    measurementId: 'G-24YD5BVX3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWw5cyiPDm7ZVGnCH9wjT-4o0oygeYTrc',
    appId: '1:624903561185:android:7c204801b480651af8fca0',
    messagingSenderId: '624903561185',
    projectId: 'instafeed-60a74',
    storageBucket: 'instafeed-60a74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBALLSz62a913Hq9vZjX8pMp5uUEHr9Zus',
    appId: '1:624903561185:ios:401d5ee6debafca6f8fca0',
    messagingSenderId: '624903561185',
    projectId: 'instafeed-60a74',
    storageBucket: 'instafeed-60a74.appspot.com',
    iosClientId: '624903561185-d3ern9bn987ohtbnhm78rm9i2hrd0enu.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBALLSz62a913Hq9vZjX8pMp5uUEHr9Zus',
    appId: '1:624903561185:ios:5fc453153e22d9a3f8fca0',
    messagingSenderId: '624903561185',
    projectId: 'instafeed-60a74',
    storageBucket: 'instafeed-60a74.appspot.com',
    iosClientId: '624903561185-n3j91upk73qd7u3mcfpc1eijjf9v2gos.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialChatApp.RunnerTests',
  );
}
